### ISSUE TITLE
Throws an error on some ternary expressions

### ISSUE THREAD

**Issue by eTorAken** [ihordiachenko/eslint-plugin-chai-friendly#1]
Hi,

First of all, thanks for your plugin! We integrated it to our project and it works like a charm 👍 

However, we are experiencing a difference with the native ESLint `no-unused-expressions`. It seems to throw an error with that kind of ternary expressions:
```jsx
this.refInput ? this.refInput.focus() : this.refInner.focus(); 
// => throws "Expected an assignment or function call and instead saw en expression.
// (chai-friendly/no-unused-expressions)"
```

We have to write it that way to make it pass:
```jsx
if(this.refInput) {
  this.refInput.focus();
}
else {
  this.refInner.focus();
}
```
but it's way less easier to read and write.

FYI, this is not a problem when using native rule from `eslint@3.17.0`.

**Comment by ihordiachenko** [comment]
Hi, thanks for your feedback!

You can use the `allowTernary` option to allow this pattern:

```json
{
  "rules": {
    "chai-friendly/no-unused-expressions": ["error", {"allowTernary": true}]
  }
}
```
Plugin supports all original rule's [options](http://eslint.org/docs/rules/no-unused-expressions#options). I'll add them to readme too.

**Comment by eTorAken** [comment]
Thanks for this precision. Indeed, I think it might be important to speak about it in the readme as I did not find it that obvious.

Thanks!
