### ISSUE TITLE
how to configure with standardjs

### ISSUE THREAD

**Issue by kdhttps** [ihordiachenko/eslint-plugin-chai-friendly#16]
I've tried to add it in package.json for standardjs configuration

```
"plugins": [
      "chai-friendly"
    ]
```

but as standard has zero configuration, it is not allow to add `rules` so is there any other way, please suggest.

**Comment by ihordiachenko** [comment]
Hi, @kdhttps

I think it's not possible with `standard` package, but you can use [eslint-config-standard](https://github.com/standard/eslint-config-standard) preset instead. This approach allows customizing the eslint rules as usual.

**Comment by kdhttps** [comment]
I've used [standardx](https://github.com/standard/standardx) which allow me to use `chai-friendly` with standardjs.

Thank you @ihordiachenko   :)
