### ISSUE TITLE
Support chai "should" usage

### ISSUE THREAD

**Issue by zxlin** [ihordiachenko/eslint-plugin-chai-friendly#3]
Hi thanks for the work on this package, I wanted to know if there's any support for the `should` usage of chai. Looking at the code, it seems like it's only looking for the `expect` call. If it doesn't already support the should usage, do you have any plans of including it?

**Comment by ihordiachenko** [comment]
Hi, appreciate your feedback! Yes, `should` statements are not supported yet. I'm going to include this feature in the next release. Most likely it will be available by the start of next week.
