### ISSUE TITLE
ESLint 9 / Flat config

### ISSUE THREAD

**Issue by brettz9** [ihordiachenko/eslint-plugin-chai-friendly#31]
Hi,

As of ESLint 8, there is now a new format for ESLint config files which requires that plugins follow a specific format. In ESLint 9, this format will be the only one available by default (and other API changes have occurred in ESLint 9 that may affect this plugin).

Info:

1. https://eslint.org/docs/latest/use/configure/configuration-files-new
1. https://eslint.org/blog/2022/08/new-config-system-part-1/
1. https://eslint.org/blog/2022/08/new-config-system-part-2/
1. https://eslint.org/docs/latest/use/configure/migration-guide

Might you update to be compatible with the new format?

Thanks!

**Comment by ihordiachenko** [comment]
Hi @brettz9! Will look into it soon

**Comment by ihordiachenko** [comment]
Hi @brettz9! Could you take a look at the flat config support implementation #34 ?

**Comment by ihordiachenko** [comment]
@brettz9 released in `eslint-plugin-chai-friendly@0.8.0`

**Comment by brettz9** [comment]
Awesome, thanks so much!
