### ISSUE TITLE
Offer "recommended config"

### ISSUE THREAD

**Issue by brettz9** [ihordiachenko/eslint-plugin-chai-friendly#6]
I'd just like to suggest making things a little simpler by offering a "recommended" config which enables your rule, disables `no-unused-expressions`, and adds your plugin to `plugins` automatically, so one only need to add your plugin to `extends`...

**Comment by ihordiachenko** [comment]
@brettz9 thanks for your contribution

**Comment by brettz9** [comment]
Thanks for your prompt reviews and publishing! And thanks for the very useful plugin!
